#header {
position: relative;
color: #888888;
-moz-border-radius-bottomleft: 6px;
-webkit-border-bottom-left-radius: 6px;
border-bottom-left-radius: 6px;
-moz-border-radius-bottomright: 6px;
-webkit-border-bottom-right-radius: 6px;
border-bottom-right-radius: 6px;
margin-bottom: 12px;
padding-top: 30px;
background-repeat: no-repeat;
z-index: 9;
margin-bottom: 50px;